### ISSUE TITLE
Cannot read data when rendering page - api is installed

### ISSUE THREAD

**Issue by Konijntje-x** [creativetimofficial/nuxt-argon-dashboard-laravel-bs4#1]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Yes] I am running the latest version
- [Yes ] I checked the documentation and found no answer
- [ Yes] I checked to make sure that this issue has not already been filed
- [Yes ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting
I expext the dashboard.

# Current Behavior

What is the current behavior?
I log in with  admin@jsonapi.com on my own localhost, npm run dev typed in console. I can insert admin@jsonapi.com and password, hit log in and i become "Cannot read property 'data' of undefined
An error occurred while rendering the page. Check developer tools console for details."
I've also set api. 
# Failure Informat ion (for bugs)
![image](https://user-images.githubusercontent.com/75688952/103485186-e5eff780-4df4-11eb-956c-7e2c314b51bd.png)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: acer
* Operating System: windows 10
* Browser and Version: google chrome, newest
IMPORTANT: same issue with registering
IMPORTZNT: i have a notification on my device from lavarel that the build is succesfull.

## Failure Logs

Please include any relevant log snippets or files here.
I haven't

**Comment by teamupdivision** [comment]
Hi @Konijntje-x,

Thanks for using Creative Tim products. 

Do you use **php artisan serve**?

If yes, please use a proper multi-threaded web server such as Apache or Nginix to serve the backend application. Do not use php artisan serve as it will result in stalled requests due to the single-threaded nature of the built-in PHP web server.
We strongly recommend using Laradock or Laragon if possible.

Thank you.

**Comment by teamupdivision** [comment]
Hi @Konijntje-x,

We would like to check if this helped in solving the issue. 
Should you need any further information feel free to contact us.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi @Konijntje-x,

Hope this solved the problem. I will go ahead and close this ticket.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).

**Comment by appmeicher** [comment]
Hello I am having the same issue, using a debian 9 apache virtual host, can you help please?

**Comment by teamupdivision** [comment]
Hi @appmeicher,

Can you please give us some more details regarding your issue?

Thank you,
UPDIVISION Team

**Comment by appmeicher** [comment]
I installed both the api and the nuxt app on a debian 9 apache with virtual server, when I call the login POST api from postman it ruturns 200, when I try to login from the nuxt app ti gives the page: "Cannot read property 'data' of undefined
An error occurred while rendering the page. Check developer tools console for details."
This comes from the validateApi function present on the login page, so the error comes from the server
I guess I am missing some passport configuration but I have not been able to find the origin of the issue

**Comment by teamupdivision** [comment]
Hi @appmeicher,

Thank you for this extra info. Can you please also send us the .env files of the projects?

Best,
UPDIVISION Team

**Comment by appmeicher** [comment]
of course, thanks!

API SERVER:

APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:/=
APP_DEBUG=true
APP_URL=http://nuxt-server.test

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=nuxt-server
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"



NUXT APP:

BASE_URL=http://nuxt-server.test
API_BASE_URL=http://nuxt-server.test
API_KEY=
IS_DEMO=

**Comment by teamupdivision** [comment]
Hello @appmeicher,

`BASE_URL `should contain the URL of your Nuxt Argon Dashboard Project (eg. http://localhost:8080/). Right now it has the same value with your `API_BASE_URL`.

Please let us know if you encounter any other issues.

Best,
UPDIVISION Team

**Comment by appmeicher** [comment]
thanks for the tip, I changed the .env of the nuxt app and the related networka nd apache configuration

now when trying to login, on the route http://nuxt-server.test/api/v1/login it goes 200 and goes ahed on the http://nuxt-server.test/api/v1/me, returning 200 also, but not actually loggin in...

same behavour If login with wrong credentials....

**Comment by teamupdivision** [comment]
Hi @appmeicher,

Can you please let us know what response are you getting from the /me route?

Thank you,
UPDIVISION Team

**Comment by appmeicher** [comment]
from the nuxt app is this, even if with wrong credentials, or if logging in with credentials of user n°2:
{data: {type: "users", id: "1",…}}
data: {type: "users", id: "1",…}
attributes: {name: "Admin", email: "admin@jsonapi.com", created_at: "2022-07-19 08:24:11",…}
id: "1"
links: {self: "http://nuxt-server.test/api/v1/users/1"}
self: "http://nuxt-server.test/api/v1/users/1"
type: "users"

by the way, I was able to register a new user but I was locked put, cant access the dashboard... If loggin with postman, everything works fine (error if wrong credentials, get right user with the right credentials

**Comment by teamupdivision** [comment]
Hi @appmeicher,

Did you make any modifications to the code? Also, can you please send the response from the register too?

Thank you,
UPDIVISION Team

**Comment by appmeicher** [comment]
Hi, thanks a lot for your support! I must have messed something with the nuxt app code, the main problem was surely in the .env API_BASE_URL, missing the /api/v1 part, sorry for my numbness!! I'll by the pro version right away!

**Comment by teamupdivision** [comment]
Hi @appmeicher,

We are glad we could help. Thank you for using our products!

If you encounter any other issues, don't hesitate to let us know.

Best,
UPDIVISION Team
